//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 4.0.30319.42000
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Xml.Serialization;

//
//Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
//

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false) 
class factura {
    
    private var infoTributariaField : infoTributaria;
    
    private var infoFacturaField : facturaInfoFactura;
    
    private var detallesField : facturaDetalle[];
    
    private var reembolsosField : reembolsosReembolsoDetalle[];
    
    private var tipoNegociableField : tipoNegociable;
    
    private var maquinaFiscalField : maquinaFiscal;
    
    private var infoAdicionalField : facturaCampoAdicional[];
    
    private var signatureField : SignatureType;
    
    private var idField : facturaID;
    
    private var idFieldSpecified : boolean;
    
    private var versionField : System.String;
    
    ///<remarks/>
    public final function get infoTributaria() : infoTributaria {
        return this.infoTributariaField;
    }
    public final function set infoTributaria(value : infoTributaria) {
        this.infoTributariaField = value;
    }
    
    ///<remarks/>
    public final function get infoFactura() : facturaInfoFactura {
        return this.infoFacturaField;
    }
    public final function set infoFactura(value : facturaInfoFactura) {
        this.infoFacturaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("detalle", IsNullable=false) 
    function get detalles() : facturaDetalle[] {
        return this.detallesField;
    }
    public final function set detalles(value : facturaDetalle[]) {
        this.detallesField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("reembolsoDetalle", IsNullable=false) 
    function get reembolsos() : reembolsosReembolsoDetalle[] {
        return this.reembolsosField;
    }
    public final function set reembolsos(value : reembolsosReembolsoDetalle[]) {
        this.reembolsosField = value;
    }
    
    ///<remarks/>
    public final function get tipoNegociable() : tipoNegociable {
        return this.tipoNegociableField;
    }
    public final function set tipoNegociable(value : tipoNegociable) {
        this.tipoNegociableField = value;
    }
    
    ///<remarks/>
    public final function get maquinaFiscal() : maquinaFiscal {
        return this.maquinaFiscalField;
    }
    public final function set maquinaFiscal(value : maquinaFiscal) {
        this.maquinaFiscalField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("campoAdicional", IsNullable=false) 
    function get infoAdicional() : facturaCampoAdicional[] {
        return this.infoAdicionalField;
    }
    public final function set infoAdicional(value : facturaCampoAdicional[]) {
        this.infoAdicionalField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") 
    function get Signature() : SignatureType {
        return this.signatureField;
    }
    public final function set Signature(value : SignatureType) {
        this.signatureField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get id() : facturaID {
        return this.idField;
    }
    public final function set id(value : facturaID) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get idSpecified() : boolean {
        return this.idFieldSpecified;
    }
    public final function set idSpecified(value : boolean) {
        this.idFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get version() : System.String {
        return this.versionField;
    }
    public final function set version(value : System.String) {
        this.versionField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class infoTributaria {
    
    private var ambienteField : System.String;
    
    private var tipoEmisionField : System.String;
    
    private var razonSocialField : System.String;
    
    private var nombreComercialField : System.String;
    
    private var rucField : System.String;
    
    private var claveAccesoField : System.String;
    
    private var codDocField : System.String;
    
    private var estabField : System.String;
    
    private var ptoEmiField : System.String;
    
    private var secuencialField : System.String;
    
    private var dirMatrizField : System.String;
    
    private var agenteRetencionField : System.String;
    
    private var contribuyenteRimpeField : System.String;
    
    ///<remarks/>
    public final function get ambiente() : System.String {
        return this.ambienteField;
    }
    public final function set ambiente(value : System.String) {
        this.ambienteField = value;
    }
    
    ///<remarks/>
    public final function get tipoEmision() : System.String {
        return this.tipoEmisionField;
    }
    public final function set tipoEmision(value : System.String) {
        this.tipoEmisionField = value;
    }
    
    ///<remarks/>
    public final function get razonSocial() : System.String {
        return this.razonSocialField;
    }
    public final function set razonSocial(value : System.String) {
        this.razonSocialField = value;
    }
    
    ///<remarks/>
    public final function get nombreComercial() : System.String {
        return this.nombreComercialField;
    }
    public final function set nombreComercial(value : System.String) {
        this.nombreComercialField = value;
    }
    
    ///<remarks/>
    public final function get ruc() : System.String {
        return this.rucField;
    }
    public final function set ruc(value : System.String) {
        this.rucField = value;
    }
    
    ///<remarks/>
    public final function get claveAcceso() : System.String {
        return this.claveAccesoField;
    }
    public final function set claveAcceso(value : System.String) {
        this.claveAccesoField = value;
    }
    
    ///<remarks/>
    public final function get codDoc() : System.String {
        return this.codDocField;
    }
    public final function set codDoc(value : System.String) {
        this.codDocField = value;
    }
    
    ///<remarks/>
    public final function get estab() : System.String {
        return this.estabField;
    }
    public final function set estab(value : System.String) {
        this.estabField = value;
    }
    
    ///<remarks/>
    public final function get ptoEmi() : System.String {
        return this.ptoEmiField;
    }
    public final function set ptoEmi(value : System.String) {
        this.ptoEmiField = value;
    }
    
    ///<remarks/>
    public final function get secuencial() : System.String {
        return this.secuencialField;
    }
    public final function set secuencial(value : System.String) {
        this.secuencialField = value;
    }
    
    ///<remarks/>
    public final function get dirMatriz() : System.String {
        return this.dirMatrizField;
    }
    public final function set dirMatriz(value : System.String) {
        this.dirMatrizField = value;
    }
    
    ///<remarks/>
    public final function get agenteRetencion() : System.String {
        return this.agenteRetencionField;
    }
    public final function set agenteRetencion(value : System.String) {
        this.agenteRetencionField = value;
    }
    
    ///<remarks/>
    public final function get contribuyenteRimpe() : System.String {
        return this.contribuyenteRimpeField;
    }
    public final function set contribuyenteRimpe(value : System.String) {
        this.contribuyenteRimpeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class ObjectType {
    
    private var anyField : System.Xml.XmlNode[];
    
    private var idField : System.String;
    
    private var mimeTypeField : System.String;
    
    private var encodingField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlNode[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlNode[]) {
        this.anyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get MimeType() : System.String {
        return this.mimeTypeField;
    }
    public final function set MimeType(value : System.String) {
        this.mimeTypeField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Encoding() : System.String {
        return this.encodingField;
    }
    public final function set Encoding(value : System.String) {
        this.encodingField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SPKIDataType {
    
    private var sPKISexpField : byte[][];
    
    private var anyField : System.Xml.XmlElement;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary") 
    function get SPKISexp() : byte[][] {
        return this.sPKISexpField;
    }
    public final function set SPKISexp(value : byte[][]) {
        this.sPKISexpField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlElement {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlElement) {
        this.anyField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class PGPDataType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType1[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() System.Xml.Serialization.XmlElementAttribute("PGPKeyID", byte[], DataType="base64Binary") System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", byte[], DataType="base64Binary") System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType1[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType1[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false) 
enum ItemsChoiceType1 {
    
    ///<remarks/>
    Item,
    
    ///<remarks/>
    PGPKeyID,
    
    ///<remarks/>
    PGPKeyPacket,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") 
class X509IssuerSerialType {
    
    private var x509IssuerNameField : System.String;
    
    private var x509SerialNumberField : System.String;
    
    ///<remarks/>
    public final function get X509IssuerName() : System.String {
        return this.x509IssuerNameField;
    }
    public final function set X509IssuerName(value : System.String) {
        this.x509IssuerNameField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="integer") 
    function get X509SerialNumber() : System.String {
        return this.x509SerialNumberField;
    }
    public final function set X509SerialNumber(value : System.String) {
        this.x509SerialNumberField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class X509DataType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() System.Xml.Serialization.XmlElementAttribute("X509CRL", byte[], DataType="base64Binary") System.Xml.Serialization.XmlElementAttribute("X509Certificate", byte[], DataType="base64Binary") System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", X509IssuerSerialType) System.Xml.Serialization.XmlElementAttribute("X509SKI", byte[], DataType="base64Binary") System.Xml.Serialization.XmlElementAttribute("X509SubjectName", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false) 
enum ItemsChoiceType {
    
    ///<remarks/>
    Item,
    
    ///<remarks/>
    X509CRL,
    
    ///<remarks/>
    X509Certificate,
    
    ///<remarks/>
    X509IssuerSerial,
    
    ///<remarks/>
    X509SKI,
    
    ///<remarks/>
    X509SubjectName,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class RetrievalMethodType {
    
    private var transformsField : TransformType[];
    
    private var uRIField : System.String;
    
    private var typeField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false) 
    function get Transforms() : TransformType[] {
        return this.transformsField;
    }
    public final function set Transforms(value : TransformType[]) {
        this.transformsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get URI() : System.String {
        return this.uRIField;
    }
    public final function set URI(value : System.String) {
        this.uRIField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Type() : System.String {
        return this.typeField;
    }
    public final function set Type(value : System.String) {
        this.typeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class TransformType {
    
    private var itemsField : System.Object[];
    
    private var textField : System.String[];
    
    private var algorithmField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() System.Xml.Serialization.XmlElementAttribute("XPath", System.String) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() 
    function get Text() : System.String[] {
        return this.textField;
    }
    public final function set Text(value : System.String[]) {
        this.textField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Algorithm() : System.String {
        return this.algorithmField;
    }
    public final function set Algorithm(value : System.String) {
        this.algorithmField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class RSAKeyValueType {
    
    private var modulusField : byte[];
    
    private var exponentField : byte[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get Modulus() : byte[] {
        return this.modulusField;
    }
    public final function set Modulus(value : byte[]) {
        this.modulusField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get Exponent() : byte[] {
        return this.exponentField;
    }
    public final function set Exponent(value : byte[]) {
        this.exponentField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class DSAKeyValueType {
    
    private var pField : byte[];
    
    private var qField : byte[];
    
    private var gField : byte[];
    
    private var yField : byte[];
    
    private var jField : byte[];
    
    private var seedField : byte[];
    
    private var pgenCounterField : byte[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get P() : byte[] {
        return this.pField;
    }
    public final function set P(value : byte[]) {
        this.pField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get Q() : byte[] {
        return this.qField;
    }
    public final function set Q(value : byte[]) {
        this.qField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get G() : byte[] {
        return this.gField;
    }
    public final function set G(value : byte[]) {
        this.gField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get Y() : byte[] {
        return this.yField;
    }
    public final function set Y(value : byte[]) {
        this.yField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get J() : byte[] {
        return this.jField;
    }
    public final function set J(value : byte[]) {
        this.jField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get Seed() : byte[] {
        return this.seedField;
    }
    public final function set Seed(value : byte[]) {
        this.seedField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get PgenCounter() : byte[] {
        return this.pgenCounterField;
    }
    public final function set PgenCounter(value : byte[]) {
        this.pgenCounterField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class KeyValueType {
    
    private var itemField : System.Object;
    
    private var textField : System.String[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", DSAKeyValueType) System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", RSAKeyValueType) 
    function get Item() : System.Object {
        return this.itemField;
    }
    public final function set Item(value : System.Object) {
        this.itemField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() 
    function get Text() : System.String[] {
        return this.textField;
    }
    public final function set Text(value : System.String[]) {
        this.textField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class KeyInfoType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType2[];
    
    private var textField : System.String[];
    
    private var idField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() System.Xml.Serialization.XmlElementAttribute("KeyName", System.String) System.Xml.Serialization.XmlElementAttribute("KeyValue", KeyValueType) System.Xml.Serialization.XmlElementAttribute("MgmtData", System.String) System.Xml.Serialization.XmlElementAttribute("PGPData", PGPDataType) System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", RetrievalMethodType) System.Xml.Serialization.XmlElementAttribute("SPKIData", SPKIDataType) System.Xml.Serialization.XmlElementAttribute("X509Data", X509DataType) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType2[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType2[]) {
        this.itemsElementNameField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() 
    function get Text() : System.String[] {
        return this.textField;
    }
    public final function set Text(value : System.String[]) {
        this.textField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false) 
enum ItemsChoiceType2 {
    
    ///<remarks/>
    Item,
    
    ///<remarks/>
    KeyName,
    
    ///<remarks/>
    KeyValue,
    
    ///<remarks/>
    MgmtData,
    
    ///<remarks/>
    PGPData,
    
    ///<remarks/>
    RetrievalMethod,
    
    ///<remarks/>
    SPKIData,
    
    ///<remarks/>
    X509Data,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignatureValueType {
    
    private var idField : System.String;
    
    private var valueField : byte[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary") 
    function get Value() : byte[] {
        return this.valueField;
    }
    public final function set Value(value : byte[]) {
        this.valueField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class DigestMethodType {
    
    private var anyField : System.Xml.XmlNode[];
    
    private var algorithmField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlNode[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlNode[]) {
        this.anyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Algorithm() : System.String {
        return this.algorithmField;
    }
    public final function set Algorithm(value : System.String) {
        this.algorithmField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class ReferenceType {
    
    private var transformsField : TransformType[];
    
    private var digestMethodField : DigestMethodType;
    
    private var digestValueField : byte[];
    
    private var idField : System.String;
    
    private var uRIField : System.String;
    
    private var typeField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false) 
    function get Transforms() : TransformType[] {
        return this.transformsField;
    }
    public final function set Transforms(value : TransformType[]) {
        this.transformsField = value;
    }
    
    ///<remarks/>
    public final function get DigestMethod() : DigestMethodType {
        return this.digestMethodField;
    }
    public final function set DigestMethod(value : DigestMethodType) {
        this.digestMethodField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary") 
    function get DigestValue() : byte[] {
        return this.digestValueField;
    }
    public final function set DigestValue(value : byte[]) {
        this.digestValueField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get URI() : System.String {
        return this.uRIField;
    }
    public final function set URI(value : System.String) {
        this.uRIField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Type() : System.String {
        return this.typeField;
    }
    public final function set Type(value : System.String) {
        this.typeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignatureMethodType {
    
    private var hMACOutputLengthField : System.String;
    
    private var anyField : System.Xml.XmlNode[];
    
    private var algorithmField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute(DataType="integer") 
    function get HMACOutputLength() : System.String {
        return this.hMACOutputLengthField;
    }
    public final function set HMACOutputLength(value : System.String) {
        this.hMACOutputLengthField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlNode[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlNode[]) {
        this.anyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Algorithm() : System.String {
        return this.algorithmField;
    }
    public final function set Algorithm(value : System.String) {
        this.algorithmField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class CanonicalizationMethodType {
    
    private var anyField : System.Xml.XmlNode[];
    
    private var algorithmField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Any() : System.Xml.XmlNode[] {
        return this.anyField;
    }
    public final function set Any(value : System.Xml.XmlNode[]) {
        this.anyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Algorithm() : System.String {
        return this.algorithmField;
    }
    public final function set Algorithm(value : System.String) {
        this.algorithmField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignedInfoType {
    
    private var canonicalizationMethodField : CanonicalizationMethodType;
    
    private var signatureMethodField : SignatureMethodType;
    
    private var referenceField : ReferenceType[];
    
    private var idField : System.String;
    
    ///<remarks/>
    public final function get CanonicalizationMethod() : CanonicalizationMethodType {
        return this.canonicalizationMethodField;
    }
    public final function set CanonicalizationMethod(value : CanonicalizationMethodType) {
        this.canonicalizationMethodField = value;
    }
    
    ///<remarks/>
    public final function get SignatureMethod() : SignatureMethodType {
        return this.signatureMethodField;
    }
    public final function set SignatureMethod(value : SignatureMethodType) {
        this.signatureMethodField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("Reference") 
    function get Reference() : ReferenceType[] {
        return this.referenceField;
    }
    public final function set Reference(value : ReferenceType[]) {
        this.referenceField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignatureType {
    
    private var signedInfoField : SignedInfoType;
    
    private var signatureValueField : SignatureValueType;
    
    private var keyInfoField : KeyInfoType;
    
    private var objectField : ObjectType[];
    
    private var idField : System.String;
    
    ///<remarks/>
    public final function get SignedInfo() : SignedInfoType {
        return this.signedInfoField;
    }
    public final function set SignedInfo(value : SignedInfoType) {
        this.signedInfoField = value;
    }
    
    ///<remarks/>
    public final function get SignatureValue() : SignatureValueType {
        return this.signatureValueField;
    }
    public final function set SignatureValue(value : SignatureValueType) {
        this.signatureValueField = value;
    }
    
    ///<remarks/>
    public final function get KeyInfo() : KeyInfoType {
        return this.keyInfoField;
    }
    public final function set KeyInfo(value : KeyInfoType) {
        this.keyInfoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("Object") 
    function get Object() : ObjectType[] {
        return this.objectField;
    }
    public final function set Object(value : ObjectType[]) {
        this.objectField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class maquinaFiscal {
    
    private var marcaField : System.String;
    
    private var modeloField : System.String;
    
    private var serieField : System.String;
    
    ///<remarks/>
    public final function get marca() : System.String {
        return this.marcaField;
    }
    public final function set marca(value : System.String) {
        this.marcaField = value;
    }
    
    ///<remarks/>
    public final function get modelo() : System.String {
        return this.modeloField;
    }
    public final function set modelo(value : System.String) {
        this.modeloField = value;
    }
    
    ///<remarks/>
    public final function get serie() : System.String {
        return this.serieField;
    }
    public final function set serie(value : System.String) {
        this.serieField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class tipoNegociable {
    
    private var correoField : System.String;
    
    ///<remarks/>
    public final function get correo() : System.String {
        return this.correoField;
    }
    public final function set correo(value : System.String) {
        this.correoField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class impuesto {
    
    private var codigoField : System.String;
    
    private var codigoPorcentajeField : System.String;
    
    private var tarifaField : decimal;
    
    private var baseImponibleField : decimal;
    
    private var valorField : decimal;
    
    ///<remarks/>
    public final function get codigo() : System.String {
        return this.codigoField;
    }
    public final function set codigo(value : System.String) {
        this.codigoField = value;
    }
    
    ///<remarks/>
    public final function get codigoPorcentaje() : System.String {
        return this.codigoPorcentajeField;
    }
    public final function set codigoPorcentaje(value : System.String) {
        this.codigoPorcentajeField = value;
    }
    
    ///<remarks/>
    public final function get tarifa() : decimal {
        return this.tarifaField;
    }
    public final function set tarifa(value : decimal) {
        this.tarifaField = value;
    }
    
    ///<remarks/>
    public final function get baseImponible() : decimal {
        return this.baseImponibleField;
    }
    public final function set baseImponible(value : decimal) {
        this.baseImponibleField = value;
    }
    
    ///<remarks/>
    public final function get valor() : decimal {
        return this.valorField;
    }
    public final function set valor(value : decimal) {
        this.valorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class compensacion {
    
    private var codigoField : System.String;
    
    private var tarifaField : decimal;
    
    private var valorField : decimal;
    
    ///<remarks/>
    public final function get codigo() : System.String {
        return this.codigoField;
    }
    public final function set codigo(value : System.String) {
        this.codigoField = value;
    }
    
    ///<remarks/>
    public final function get tarifa() : decimal {
        return this.tarifaField;
    }
    public final function set tarifa(value : decimal) {
        this.tarifaField = value;
    }
    
    ///<remarks/>
    public final function get valor() : decimal {
        return this.valorField;
    }
    public final function set valor(value : decimal) {
        this.valorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class facturaInfoFactura {
    
    private var fechaEmisionField : System.String;
    
    private var dirEstablecimientoField : System.String;
    
    private var contribuyenteEspecialField : System.String;
    
    private var obligadoContabilidadField : obligadoContabilidad;
    
    private var obligadoContabilidadFieldSpecified : boolean;
    
    private var comercioExteriorField : System.String;
    
    private var incoTermFacturaField : System.String;
    
    private var lugarIncoTermField : System.String;
    
    private var paisOrigenField : System.String;
    
    private var puertoEmbarqueField : System.String;
    
    private var puertoDestinoField : System.String;
    
    private var paisDestinoField : System.String;
    
    private var paisAdquisicionField : System.String;
    
    private var tipoIdentificacionCompradorField : System.String;
    
    private var guiaRemisionField : System.String;
    
    private var razonSocialCompradorField : System.String;
    
    private var identificacionCompradorField : System.String;
    
    private var direccionCompradorField : System.String;
    
    private var totalSinImpuestosField : decimal;
    
    private var totalSubsidioField : decimal;
    
    private var totalSubsidioFieldSpecified : boolean;
    
    private var incoTermTotalSinImpuestosField : System.String;
    
    private var totalDescuentoField : decimal;
    
    private var codDocReembolsoField : System.String;
    
    private var totalComprobantesReembolsoField : decimal;
    
    private var totalComprobantesReembolsoFieldSpecified : boolean;
    
    private var totalBaseImponibleReembolsoField : decimal;
    
    private var totalBaseImponibleReembolsoFieldSpecified : boolean;
    
    private var totalImpuestoReembolsoField : decimal;
    
    private var totalImpuestoReembolsoFieldSpecified : boolean;
    
    private var totalConImpuestosField : facturaInfoFacturaTotalImpuesto[];
    
    private var compensacionesField : compensacion[];
    
    private var propinaField : decimal;
    
    private var propinaFieldSpecified : boolean;
    
    private var fleteInternacionalField : decimal;
    
    private var fleteInternacionalFieldSpecified : boolean;
    
    private var seguroInternacionalField : decimal;
    
    private var seguroInternacionalFieldSpecified : boolean;
    
    private var gastosAduanerosField : decimal;
    
    private var gastosAduanerosFieldSpecified : boolean;
    
    private var gastosTransporteOtrosField : decimal;
    
    private var gastosTransporteOtrosFieldSpecified : boolean;
    
    private var importeTotalField : decimal;
    
    private var monedaField : System.String;
    
    private var placaField : System.String;
    
    private var pagosField : pagosPago[];
    
    private var valorRetIvaField : decimal;
    
    private var valorRetIvaFieldSpecified : boolean;
    
    private var valorRetRentaField : decimal;
    
    private var valorRetRentaFieldSpecified : boolean;
    
    ///<remarks/>
    public final function get fechaEmision() : System.String {
        return this.fechaEmisionField;
    }
    public final function set fechaEmision(value : System.String) {
        this.fechaEmisionField = value;
    }
    
    ///<remarks/>
    public final function get dirEstablecimiento() : System.String {
        return this.dirEstablecimientoField;
    }
    public final function set dirEstablecimiento(value : System.String) {
        this.dirEstablecimientoField = value;
    }
    
    ///<remarks/>
    public final function get contribuyenteEspecial() : System.String {
        return this.contribuyenteEspecialField;
    }
    public final function set contribuyenteEspecial(value : System.String) {
        this.contribuyenteEspecialField = value;
    }
    
    ///<remarks/>
    public final function get obligadoContabilidad() : obligadoContabilidad {
        return this.obligadoContabilidadField;
    }
    public final function set obligadoContabilidad(value : obligadoContabilidad) {
        this.obligadoContabilidadField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get obligadoContabilidadSpecified() : boolean {
        return this.obligadoContabilidadFieldSpecified;
    }
    public final function set obligadoContabilidadSpecified(value : boolean) {
        this.obligadoContabilidadFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get comercioExterior() : System.String {
        return this.comercioExteriorField;
    }
    public final function set comercioExterior(value : System.String) {
        this.comercioExteriorField = value;
    }
    
    ///<remarks/>
    public final function get incoTermFactura() : System.String {
        return this.incoTermFacturaField;
    }
    public final function set incoTermFactura(value : System.String) {
        this.incoTermFacturaField = value;
    }
    
    ///<remarks/>
    public final function get lugarIncoTerm() : System.String {
        return this.lugarIncoTermField;
    }
    public final function set lugarIncoTerm(value : System.String) {
        this.lugarIncoTermField = value;
    }
    
    ///<remarks/>
    public final function get paisOrigen() : System.String {
        return this.paisOrigenField;
    }
    public final function set paisOrigen(value : System.String) {
        this.paisOrigenField = value;
    }
    
    ///<remarks/>
    public final function get puertoEmbarque() : System.String {
        return this.puertoEmbarqueField;
    }
    public final function set puertoEmbarque(value : System.String) {
        this.puertoEmbarqueField = value;
    }
    
    ///<remarks/>
    public final function get puertoDestino() : System.String {
        return this.puertoDestinoField;
    }
    public final function set puertoDestino(value : System.String) {
        this.puertoDestinoField = value;
    }
    
    ///<remarks/>
    public final function get paisDestino() : System.String {
        return this.paisDestinoField;
    }
    public final function set paisDestino(value : System.String) {
        this.paisDestinoField = value;
    }
    
    ///<remarks/>
    public final function get paisAdquisicion() : System.String {
        return this.paisAdquisicionField;
    }
    public final function set paisAdquisicion(value : System.String) {
        this.paisAdquisicionField = value;
    }
    
    ///<remarks/>
    public final function get tipoIdentificacionComprador() : System.String {
        return this.tipoIdentificacionCompradorField;
    }
    public final function set tipoIdentificacionComprador(value : System.String) {
        this.tipoIdentificacionCompradorField = value;
    }
    
    ///<remarks/>
    public final function get guiaRemision() : System.String {
        return this.guiaRemisionField;
    }
    public final function set guiaRemision(value : System.String) {
        this.guiaRemisionField = value;
    }
    
    ///<remarks/>
    public final function get razonSocialComprador() : System.String {
        return this.razonSocialCompradorField;
    }
    public final function set razonSocialComprador(value : System.String) {
        this.razonSocialCompradorField = value;
    }
    
    ///<remarks/>
    public final function get identificacionComprador() : System.String {
        return this.identificacionCompradorField;
    }
    public final function set identificacionComprador(value : System.String) {
        this.identificacionCompradorField = value;
    }
    
    ///<remarks/>
    public final function get direccionComprador() : System.String {
        return this.direccionCompradorField;
    }
    public final function set direccionComprador(value : System.String) {
        this.direccionCompradorField = value;
    }
    
    ///<remarks/>
    public final function get totalSinImpuestos() : decimal {
        return this.totalSinImpuestosField;
    }
    public final function set totalSinImpuestos(value : decimal) {
        this.totalSinImpuestosField = value;
    }
    
    ///<remarks/>
    public final function get totalSubsidio() : decimal {
        return this.totalSubsidioField;
    }
    public final function set totalSubsidio(value : decimal) {
        this.totalSubsidioField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalSubsidioSpecified() : boolean {
        return this.totalSubsidioFieldSpecified;
    }
    public final function set totalSubsidioSpecified(value : boolean) {
        this.totalSubsidioFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get incoTermTotalSinImpuestos() : System.String {
        return this.incoTermTotalSinImpuestosField;
    }
    public final function set incoTermTotalSinImpuestos(value : System.String) {
        this.incoTermTotalSinImpuestosField = value;
    }
    
    ///<remarks/>
    public final function get totalDescuento() : decimal {
        return this.totalDescuentoField;
    }
    public final function set totalDescuento(value : decimal) {
        this.totalDescuentoField = value;
    }
    
    ///<remarks/>
    public final function get codDocReembolso() : System.String {
        return this.codDocReembolsoField;
    }
    public final function set codDocReembolso(value : System.String) {
        this.codDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get totalComprobantesReembolso() : decimal {
        return this.totalComprobantesReembolsoField;
    }
    public final function set totalComprobantesReembolso(value : decimal) {
        this.totalComprobantesReembolsoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalComprobantesReembolsoSpecified() : boolean {
        return this.totalComprobantesReembolsoFieldSpecified;
    }
    public final function set totalComprobantesReembolsoSpecified(value : boolean) {
        this.totalComprobantesReembolsoFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get totalBaseImponibleReembolso() : decimal {
        return this.totalBaseImponibleReembolsoField;
    }
    public final function set totalBaseImponibleReembolso(value : decimal) {
        this.totalBaseImponibleReembolsoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalBaseImponibleReembolsoSpecified() : boolean {
        return this.totalBaseImponibleReembolsoFieldSpecified;
    }
    public final function set totalBaseImponibleReembolsoSpecified(value : boolean) {
        this.totalBaseImponibleReembolsoFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get totalImpuestoReembolso() : decimal {
        return this.totalImpuestoReembolsoField;
    }
    public final function set totalImpuestoReembolso(value : decimal) {
        this.totalImpuestoReembolsoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get totalImpuestoReembolsoSpecified() : boolean {
        return this.totalImpuestoReembolsoFieldSpecified;
    }
    public final function set totalImpuestoReembolsoSpecified(value : boolean) {
        this.totalImpuestoReembolsoFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("totalImpuesto", IsNullable=false) 
    function get totalConImpuestos() : facturaInfoFacturaTotalImpuesto[] {
        return this.totalConImpuestosField;
    }
    public final function set totalConImpuestos(value : facturaInfoFacturaTotalImpuesto[]) {
        this.totalConImpuestosField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false) 
    function get compensaciones() : compensacion[] {
        return this.compensacionesField;
    }
    public final function set compensaciones(value : compensacion[]) {
        this.compensacionesField = value;
    }
    
    ///<remarks/>
    public final function get propina() : decimal {
        return this.propinaField;
    }
    public final function set propina(value : decimal) {
        this.propinaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get propinaSpecified() : boolean {
        return this.propinaFieldSpecified;
    }
    public final function set propinaSpecified(value : boolean) {
        this.propinaFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get fleteInternacional() : decimal {
        return this.fleteInternacionalField;
    }
    public final function set fleteInternacional(value : decimal) {
        this.fleteInternacionalField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get fleteInternacionalSpecified() : boolean {
        return this.fleteInternacionalFieldSpecified;
    }
    public final function set fleteInternacionalSpecified(value : boolean) {
        this.fleteInternacionalFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get seguroInternacional() : decimal {
        return this.seguroInternacionalField;
    }
    public final function set seguroInternacional(value : decimal) {
        this.seguroInternacionalField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get seguroInternacionalSpecified() : boolean {
        return this.seguroInternacionalFieldSpecified;
    }
    public final function set seguroInternacionalSpecified(value : boolean) {
        this.seguroInternacionalFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get gastosAduaneros() : decimal {
        return this.gastosAduanerosField;
    }
    public final function set gastosAduaneros(value : decimal) {
        this.gastosAduanerosField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get gastosAduanerosSpecified() : boolean {
        return this.gastosAduanerosFieldSpecified;
    }
    public final function set gastosAduanerosSpecified(value : boolean) {
        this.gastosAduanerosFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get gastosTransporteOtros() : decimal {
        return this.gastosTransporteOtrosField;
    }
    public final function set gastosTransporteOtros(value : decimal) {
        this.gastosTransporteOtrosField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get gastosTransporteOtrosSpecified() : boolean {
        return this.gastosTransporteOtrosFieldSpecified;
    }
    public final function set gastosTransporteOtrosSpecified(value : boolean) {
        this.gastosTransporteOtrosFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get importeTotal() : decimal {
        return this.importeTotalField;
    }
    public final function set importeTotal(value : decimal) {
        this.importeTotalField = value;
    }
    
    ///<remarks/>
    public final function get moneda() : System.String {
        return this.monedaField;
    }
    public final function set moneda(value : System.String) {
        this.monedaField = value;
    }
    
    ///<remarks/>
    public final function get placa() : System.String {
        return this.placaField;
    }
    public final function set placa(value : System.String) {
        this.placaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("pago", IsNullable=false) 
    function get pagos() : pagosPago[] {
        return this.pagosField;
    }
    public final function set pagos(value : pagosPago[]) {
        this.pagosField = value;
    }
    
    ///<remarks/>
    public final function get valorRetIva() : decimal {
        return this.valorRetIvaField;
    }
    public final function set valorRetIva(value : decimal) {
        this.valorRetIvaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get valorRetIvaSpecified() : boolean {
        return this.valorRetIvaFieldSpecified;
    }
    public final function set valorRetIvaSpecified(value : boolean) {
        this.valorRetIvaFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get valorRetRenta() : decimal {
        return this.valorRetRentaField;
    }
    public final function set valorRetRenta(value : decimal) {
        this.valorRetRentaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get valorRetRentaSpecified() : boolean {
        return this.valorRetRentaFieldSpecified;
    }
    public final function set valorRetRentaSpecified(value : boolean) {
        this.valorRetRentaFieldSpecified = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() 
enum obligadoContabilidad {
    
    ///<remarks/>
    SI,
    
    ///<remarks/>
    NO,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class facturaInfoFacturaTotalImpuesto {
    
    private var codigoField : System.String;
    
    private var codigoPorcentajeField : System.String;
    
    private var descuentoAdicionalField : decimal;
    
    private var descuentoAdicionalFieldSpecified : boolean;
    
    private var baseImponibleField : decimal;
    
    private var tarifaField : decimal;
    
    private var tarifaFieldSpecified : boolean;
    
    private var valorField : decimal;
    
    private var valorDevolucionIvaField : decimal;
    
    private var valorDevolucionIvaFieldSpecified : boolean;
    
    ///<remarks/>
    public final function get codigo() : System.String {
        return this.codigoField;
    }
    public final function set codigo(value : System.String) {
        this.codigoField = value;
    }
    
    ///<remarks/>
    public final function get codigoPorcentaje() : System.String {
        return this.codigoPorcentajeField;
    }
    public final function set codigoPorcentaje(value : System.String) {
        this.codigoPorcentajeField = value;
    }
    
    ///<remarks/>
    public final function get descuentoAdicional() : decimal {
        return this.descuentoAdicionalField;
    }
    public final function set descuentoAdicional(value : decimal) {
        this.descuentoAdicionalField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get descuentoAdicionalSpecified() : boolean {
        return this.descuentoAdicionalFieldSpecified;
    }
    public final function set descuentoAdicionalSpecified(value : boolean) {
        this.descuentoAdicionalFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get baseImponible() : decimal {
        return this.baseImponibleField;
    }
    public final function set baseImponible(value : decimal) {
        this.baseImponibleField = value;
    }
    
    ///<remarks/>
    public final function get tarifa() : decimal {
        return this.tarifaField;
    }
    public final function set tarifa(value : decimal) {
        this.tarifaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get tarifaSpecified() : boolean {
        return this.tarifaFieldSpecified;
    }
    public final function set tarifaSpecified(value : boolean) {
        this.tarifaFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get valor() : decimal {
        return this.valorField;
    }
    public final function set valor(value : decimal) {
        this.valorField = value;
    }
    
    ///<remarks/>
    public final function get valorDevolucionIva() : decimal {
        return this.valorDevolucionIvaField;
    }
    public final function set valorDevolucionIva(value : decimal) {
        this.valorDevolucionIvaField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get valorDevolucionIvaSpecified() : boolean {
        return this.valorDevolucionIvaFieldSpecified;
    }
    public final function set valorDevolucionIvaSpecified(value : boolean) {
        this.valorDevolucionIvaFieldSpecified = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class pagosPago {
    
    private var formaPagoField : System.String;
    
    private var totalField : decimal;
    
    private var plazoField : decimal;
    
    private var plazoFieldSpecified : boolean;
    
    private var unidadTiempoField : System.String;
    
    ///<remarks/>
    public final function get formaPago() : System.String {
        return this.formaPagoField;
    }
    public final function set formaPago(value : System.String) {
        this.formaPagoField = value;
    }
    
    ///<remarks/>
    public final function get total() : decimal {
        return this.totalField;
    }
    public final function set total(value : decimal) {
        this.totalField = value;
    }
    
    ///<remarks/>
    public final function get plazo() : decimal {
        return this.plazoField;
    }
    public final function set plazo(value : decimal) {
        this.plazoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get plazoSpecified() : boolean {
        return this.plazoFieldSpecified;
    }
    public final function set plazoSpecified(value : boolean) {
        this.plazoFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get unidadTiempo() : System.String {
        return this.unidadTiempoField;
    }
    public final function set unidadTiempo(value : System.String) {
        this.unidadTiempoField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class facturaDetalle {
    
    private var codigoPrincipalField : System.String;
    
    private var codigoAuxiliarField : System.String;
    
    private var descripcionField : System.String;
    
    private var unidadMedidaField : System.String;
    
    private var cantidadField : decimal;
    
    private var precioUnitarioField : decimal;
    
    private var precioSinSubsidioField : decimal;
    
    private var precioSinSubsidioFieldSpecified : boolean;
    
    private var descuentoField : decimal;
    
    private var precioTotalSinImpuestoField : decimal;
    
    private var detallesAdicionalesField : facturaDetalleDetAdicional[];
    
    private var impuestosField : impuesto[];
    
    ///<remarks/>
    public final function get codigoPrincipal() : System.String {
        return this.codigoPrincipalField;
    }
    public final function set codigoPrincipal(value : System.String) {
        this.codigoPrincipalField = value;
    }
    
    ///<remarks/>
    public final function get codigoAuxiliar() : System.String {
        return this.codigoAuxiliarField;
    }
    public final function set codigoAuxiliar(value : System.String) {
        this.codigoAuxiliarField = value;
    }
    
    ///<remarks/>
    public final function get descripcion() : System.String {
        return this.descripcionField;
    }
    public final function set descripcion(value : System.String) {
        this.descripcionField = value;
    }
    
    ///<remarks/>
    public final function get unidadMedida() : System.String {
        return this.unidadMedidaField;
    }
    public final function set unidadMedida(value : System.String) {
        this.unidadMedidaField = value;
    }
    
    ///<remarks/>
    public final function get cantidad() : decimal {
        return this.cantidadField;
    }
    public final function set cantidad(value : decimal) {
        this.cantidadField = value;
    }
    
    ///<remarks/>
    public final function get precioUnitario() : decimal {
        return this.precioUnitarioField;
    }
    public final function set precioUnitario(value : decimal) {
        this.precioUnitarioField = value;
    }
    
    ///<remarks/>
    public final function get precioSinSubsidio() : decimal {
        return this.precioSinSubsidioField;
    }
    public final function set precioSinSubsidio(value : decimal) {
        this.precioSinSubsidioField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get precioSinSubsidioSpecified() : boolean {
        return this.precioSinSubsidioFieldSpecified;
    }
    public final function set precioSinSubsidioSpecified(value : boolean) {
        this.precioSinSubsidioFieldSpecified = value;
    }
    
    ///<remarks/>
    public final function get descuento() : decimal {
        return this.descuentoField;
    }
    public final function set descuento(value : decimal) {
        this.descuentoField = value;
    }
    
    ///<remarks/>
    public final function get precioTotalSinImpuesto() : decimal {
        return this.precioTotalSinImpuestoField;
    }
    public final function set precioTotalSinImpuesto(value : decimal) {
        this.precioTotalSinImpuestoField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("detAdicional", IsNullable=false) 
    function get detallesAdicionales() : facturaDetalleDetAdicional[] {
        return this.detallesAdicionalesField;
    }
    public final function set detallesAdicionales(value : facturaDetalleDetAdicional[]) {
        this.detallesAdicionalesField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false) 
    function get impuestos() : impuesto[] {
        return this.impuestosField;
    }
    public final function set impuestos(value : impuesto[]) {
        this.impuestosField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class facturaDetalleDetAdicional {
    
    private var nombreField : System.String;
    
    private var valorField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get nombre() : System.String {
        return this.nombreField;
    }
    public final function set nombre(value : System.String) {
        this.nombreField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get valor() : System.String {
        return this.valorField;
    }
    public final function set valor(value : System.String) {
        this.valorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class reembolsosReembolsoDetalle {
    
    private var tipoIdentificacionProveedorReembolsoField : System.String;
    
    private var identificacionProveedorReembolsoField : System.String;
    
    private var codPaisPagoProveedorReembolsoField : System.String;
    
    private var tipoProveedorReembolsoField : System.String;
    
    private var codDocReembolsoField : System.String;
    
    private var estabDocReembolsoField : System.String;
    
    private var ptoEmiDocReembolsoField : System.String;
    
    private var secuencialDocReembolsoField : System.String;
    
    private var fechaEmisionDocReembolsoField : System.String;
    
    private var numeroautorizacionDocReembField : System.String;
    
    private var detalleImpuestosField : detalleImpuestosDetalleImpuesto[];
    
    private var compensacionesReembolsoField : compensacion[];
    
    ///<remarks/>
    public final function get tipoIdentificacionProveedorReembolso() : System.String {
        return this.tipoIdentificacionProveedorReembolsoField;
    }
    public final function set tipoIdentificacionProveedorReembolso(value : System.String) {
        this.tipoIdentificacionProveedorReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get identificacionProveedorReembolso() : System.String {
        return this.identificacionProveedorReembolsoField;
    }
    public final function set identificacionProveedorReembolso(value : System.String) {
        this.identificacionProveedorReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get codPaisPagoProveedorReembolso() : System.String {
        return this.codPaisPagoProveedorReembolsoField;
    }
    public final function set codPaisPagoProveedorReembolso(value : System.String) {
        this.codPaisPagoProveedorReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get tipoProveedorReembolso() : System.String {
        return this.tipoProveedorReembolsoField;
    }
    public final function set tipoProveedorReembolso(value : System.String) {
        this.tipoProveedorReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get codDocReembolso() : System.String {
        return this.codDocReembolsoField;
    }
    public final function set codDocReembolso(value : System.String) {
        this.codDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get estabDocReembolso() : System.String {
        return this.estabDocReembolsoField;
    }
    public final function set estabDocReembolso(value : System.String) {
        this.estabDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get ptoEmiDocReembolso() : System.String {
        return this.ptoEmiDocReembolsoField;
    }
    public final function set ptoEmiDocReembolso(value : System.String) {
        this.ptoEmiDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get secuencialDocReembolso() : System.String {
        return this.secuencialDocReembolsoField;
    }
    public final function set secuencialDocReembolso(value : System.String) {
        this.secuencialDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get fechaEmisionDocReembolso() : System.String {
        return this.fechaEmisionDocReembolsoField;
    }
    public final function set fechaEmisionDocReembolso(value : System.String) {
        this.fechaEmisionDocReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get numeroautorizacionDocReemb() : System.String {
        return this.numeroautorizacionDocReembField;
    }
    public final function set numeroautorizacionDocReemb(value : System.String) {
        this.numeroautorizacionDocReembField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("detalleImpuesto", IsNullable=false) 
    function get detalleImpuestos() : detalleImpuestosDetalleImpuesto[] {
        return this.detalleImpuestosField;
    }
    public final function set detalleImpuestos(value : detalleImpuestosDetalleImpuesto[]) {
        this.detalleImpuestosField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlArrayItemAttribute("compensacionReembolso", IsNullable=false) 
    function get compensacionesReembolso() : compensacion[] {
        return this.compensacionesReembolsoField;
    }
    public final function set compensacionesReembolso(value : compensacion[]) {
        this.compensacionesReembolsoField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class detalleImpuestosDetalleImpuesto {
    
    private var codigoField : System.String;
    
    private var codigoPorcentajeField : System.String;
    
    private var tarifaField : decimal;
    
    private var baseImponibleReembolsoField : decimal;
    
    private var impuestoReembolsoField : decimal;
    
    ///<remarks/>
    public final function get codigo() : System.String {
        return this.codigoField;
    }
    public final function set codigo(value : System.String) {
        this.codigoField = value;
    }
    
    ///<remarks/>
    public final function get codigoPorcentaje() : System.String {
        return this.codigoPorcentajeField;
    }
    public final function set codigoPorcentaje(value : System.String) {
        this.codigoPorcentajeField = value;
    }
    
    ///<remarks/>
    public final function get tarifa() : decimal {
        return this.tarifaField;
    }
    public final function set tarifa(value : decimal) {
        this.tarifaField = value;
    }
    
    ///<remarks/>
    public final function get baseImponibleReembolso() : decimal {
        return this.baseImponibleReembolsoField;
    }
    public final function set baseImponibleReembolso(value : decimal) {
        this.baseImponibleReembolsoField = value;
    }
    
    ///<remarks/>
    public final function get impuestoReembolso() : decimal {
        return this.impuestoReembolsoField;
    }
    public final function set impuestoReembolso(value : decimal) {
        this.impuestoReembolsoField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
class facturaCampoAdicional {
    
    private var nombreField : System.String;
    
    private var valueField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get nombre() : System.String {
        return this.nombreField;
    }
    public final function set nombre(value : System.String) {
        this.nombreField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() 
    function get Value() : System.String {
        return this.valueField;
    }
    public final function set Value(value : System.String) {
        this.valueField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true) 
enum facturaID {
    
    ///<remarks/>
    comprobante,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class TransformsType {
    
    private var transformField : TransformType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("Transform") 
    function get Transform() : TransformType[] {
        return this.transformField;
    }
    public final function set Transform(value : TransformType[]) {
        this.transformField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class ManifestType {
    
    private var referenceField : ReferenceType[];
    
    private var idField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("Reference") 
    function get Reference() : ReferenceType[] {
        return this.referenceField;
    }
    public final function set Reference(value : ReferenceType[]) {
        this.referenceField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignaturePropertiesType {
    
    private var signaturePropertyField : SignaturePropertyType[];
    
    private var idField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("SignatureProperty") 
    function get SignatureProperty() : SignaturePropertyType[] {
        return this.signaturePropertyField;
    }
    public final function set SignatureProperty(value : SignaturePropertyType[]) {
        this.signaturePropertyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#") System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false) 
class SignaturePropertyType {
    
    private var itemsField : System.Xml.XmlElement[];
    
    private var textField : System.String[];
    
    private var targetField : System.String;
    
    private var idField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAnyElementAttribute() 
    function get Items() : System.Xml.XmlElement[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Xml.XmlElement[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlTextAttribute() 
    function get Text() : System.String[] {
        return this.textField;
    }
    public final function set Text(value : System.String[]) {
        this.textField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI") 
    function get Target() : System.String {
        return this.targetField;
    }
    public final function set Target(value : System.String) {
        this.targetField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute(DataType="ID") 
    function get Id() : System.String {
        return this.idField;
    }
    public final function set Id(value : System.String) {
        this.idField = value;
    }
}
